#!/usr/local/anaconda3/bin/python3
import pexpect
efit = pexpect.spawn('efitd129d')
efit.expect("type mode")
efit.sendline("2")
efit.expect("number")
efit.sendline( "1")
efit.expect("#")
efit.sendline("kfile_run")
while not efit.terminated:
	try:
		efit.expect("it=")
		lines = '%s'%efit.before
		lines = lines.split('b')[1].split("'")[1]
		lines = lines.split('\\n')
		for tline in lines:
			tline2 = tline.split('\\r')
			for item in tline2:
				if    item.find('chi')>-1: print('>>>',item)
				elif item.find('time')>-1: print('>>>',item)
				#if  item.find('kfile')>-1: print('>>>',item)
				#else: print(item)
	except: (efit.before); exit()
#show_data = efit.before
#shot_out  = show_data.split('\r\n')
#for data in shot_out: print(data)
